spring.datasource.url=jdbc:postgresql://localhost:5432/near_miss
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pavansceb@gmail.com
spring.mail.password=iujb vhvt gncz cibc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

